---
- name: Add required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - software-properties-common
      - libfontconfig1
      - musl
    state: present
    update_cache: true

- name: Download and install graphana .deb
  ansible.builtin.apt:
    deb: https://dl.grafana.com/oss/release/grafana_10.3.1_amd64.deb
    state: present
