---
# Description
- name: Install prometheus stack
  hosts: all
  gather_facts: true
  tasks:

    - name: User add for prometheus server
      ansible.builtin.user:
        comment: Automated created account for prometheus server
        create_home: false
        name: prometheus
        shell: /usr/sbin/nologin
        # state: present
        # system: true
      become: true

    - name: User add for prometheus node exporter
      ansible.builtin.user:
        comment: Automated created account for prometheus node exporter
        create_home: false
        name: node_exporter
        shell: /usr/sbin/nologin
        state: present
        system: true
      become: true

    - name: Determine latest GitHub release
      uri:
        url: "https://api.github.com/repos/prometheus/prometheus/releases/latest"
        body_format: json
      register: _github_release
      until: _github_release.status == 200
      retries: 5

    - name: Set prometheus_version
      set_fact:
        prometheus_version: "{{ _github_release.json.tag_name
          | regex_replace('^v?(.*)$', '\\1') }}"

    - name: Download and verify SHA256 checksum
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.{{ ansible_system | lower }}-amd64.tar.gz"
        dest: "/tmp/prometheus.tgz"
        checksum: "sha256:https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/sha256sums.txt"
        mode: "0644"

    - name: Unarchive prometheus server
      ansible.builtin.unarchive:
        src: /tmp/prometheus.tgz
        remote_src: true
        dest: /usr/local/bin
        include:
          - "prometheus-{{ prometheus_version }}.{{ ansible_system | lower }}-amd64/prometheus"
          - "prometheus-{{ prometheus_version }}.{{ ansible_system | lower }}-amd64/promtool"
        list_files: true # not required. If set to True, return the list of files that are contained in the tarball.
      register: server_files
      become: true

    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0644"
      with_items:
        - "/etc/prometheus"
        - "/var/lib/prometheus"
      become: true

    - name: Unarchive prometheus utility
      ansible.builtin.unarchive:
        src: /tmp/prometheus.tgz
        remote_src: true
        dest: "{{ item }}"
        include:
          - "prometheus-{{ prometheus_version }}.{{ ansible_system | lower }}-amd64/consoles"
          - "prometheus-{{ prometheus_version }}.{{ ansible_system | lower }}-amd64/console_libraries"
        list_files: true
      register: server_utility_files
      become: true
      with_items:
        - "/etc/prometheus"
        - "/var/lib/prometheus"

    - name: Change server files owner
      ansible.builtin.file:
        path: "/etc/prometheus/{{ item }}"
        mode: "0644"
        owner: prometheus
      with_items:
        - "{{ server_utility_files.results[0].files }}"
      become: true

    - name: Unarchive prometheus config
      ansible.builtin.unarchive:
        src: /tmp/prometheus.tgz
        remote_src: true
        dest: /etc/prometheus
        include:
          - "prometheus-{{ prometheus_version }}.{{ ansible_system | lower }}-amd64/prometheus.yml"
        list_files: true
      register: server_config
      become: true

    - name: Change server files owner
      ansible.builtin.file:
        path: "/etc/prometheus/prometheus-{{ prometheus_version }}.{{ ansible_system | lower }}-amd64/prometheus.yml"
        mode: "0644"
        owner: prometheus
      become: true

    - name: Determine latest GitHub release of node exporter
      ansible.builtin.uri:
        url: "https://api.github.com/repos/prometheus/node_exporter/releases/latest"
        body_format: json
      register: _github_release
      until: _github_release.status == 200
      retries: 5

    - name: Set node_exporter_version
      ansible.builtin.set_fact:
        node_exporter_version: "{{ _github_release.json.tag_name
          | regex_replace('^v?(.*)$', '\\1') }}"

    - name: Download and verify SHA256 checksum
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/\
            v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.{{ ansible_system | lower }}-amd64.tar.gz"
        dest: "/tmp/node.tgz"
        checksum: "sha256:https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/sha256sums.txt"
        mode: "0644"

    - name: Unarchive prometheus node_exporter
      ansible.builtin.unarchive:
        src: /tmp/node.tgz
        remote_src: true
        dest: /usr/local/bin
        include:
          - "node_exporter-{{ node_exporter_version }}.{{ ansible_system | lower }}-amd64/node_exporter"
        list_files: true # not required. If set to True, return the list of files that are contained in the tarball.
      register: exporter_files
      become: true

    - name: Change exporter files owner
      ansible.builtin.file:
        path: "/usr/local/bin/{{ item }}"
        mode: "0755"
        owner: node_exporter
      with_items: "{{ exporter_files.files }}"
      become: true

    - name: Create systemd node exporter service
      ansible.builtin.template:
        src: node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
        mode: "0755"
      become: true

    - name: Create systemd server service
      ansible.builtin.template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
        mode: "0755"
      become: true

